export const yearOptions = ['All','2020','2021', '2022'];

export const programOptions = ['All','Applied arts and crafts', 'Architecture', 'Design', 'Town planning', 'Engineering and Technology', 'Management', 'MCA', 'Pharmacy', 'Hotel management and catering '];

export const instituteTypes = ['All',"Unaided Private","Government","Private Aided","Deemed University Private","Deemed University Government"];
export const statesOptions = [ 
  'All',
    "Andaman & Nicobar Islands",
    "Andhra Pradesh",
    "Arunanchal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadara & Nagar Haveli",
    "Daman and Diu",  
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu & Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ]